[package]
name = "moon_workspace"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_api = { path = "../api" }
moon_cache = { path = "../cache" }
moon_common = { path = "../common" }
moon_config = { path = "../config", features = ["loader", "proto", "tracing"] }
moon_hash = { path = "../hash" }
moon_vcs = { path = "../vcs" }
miette = { workspace = true }
proto_core = { workspace = true }
starbase = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }
