[package]
name = "moon_cache_item"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Cache item utilities."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
miette = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serial_test = "3.1.1"
starbase_sandbox = { workspace = true }

[lints]
workspace = true
