[package]
name = "moon_toolchain_plugin"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A toolchain plugin, enabling new language + ecosystem support."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_pdk_api = { path = "../pdk-api" }
moon_plugin = { path = "../plugin" }
miette = { workspace = true }
proto_core = { workspace = true }
rustc-hash = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
