[package]
name = "moon_typescript_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_config = { path = "../../core/config" }
moon_error = { path = "../../core/error" }
moon_hasher = { path = "../../core/hasher" }
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_utils = { path = "../../core/utils" }
cached = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }

[dev-dependencies]
moon_test_utils = { path = "../../core/test-utils" }
