[package]
name = "moon_platform_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_config = { path = "../config" }
moon_lang = { path = "../lang" }
moon_utils = { path = "../utils" }
moon_bun_lang = { path = "../../bun/lang" }
moon_deno_lang = { path = "../../deno/lang" }
moon_go_lang = { path = "../../go/lang" }
moon_node_lang = { path = "../../node/lang" }
moon_php_lang = { path = "../../php/lang" }
moon_python_lang = { path = "../../python/lang" }
moon_ruby_lang = { path = "../../ruby/lang" }
moon_rust_lang = { path = "../../rust/lang" }
