# https://moonrepo.dev/docs/config/template
$schema: 'https://moonrepo.dev/schemas/template.json'

# REQUIRED: Name of the template in a human readable format.
title: 'Title'

# REQUIRED: Description of what the template is for and other relevant information.
description: 'Description of the template.'

# Mapping of variables that will be interpolated and rendered within template files.
# Users will be prompted to provide a value when running the generator.
variables:
  name:
    type: 'string'
    default: ''
    required: true
    prompt: 'Package name?'
