[package]
name = "moon_env_var"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Manages environment variables."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { version = "2.0.0", path = "../common" }
indexmap = { workspace = true }
miette = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
scc = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
