[package]
name = "moon_pdk"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "A plugin development kit for creating moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "1.0.1", path = "../common" }
moon_pdk_api = { version = "1.0.1", path = "../pdk-api" }
moon_project = { version = "1.0.1", path = "../project" }
moon_task = { version = "1.0.1", path = "../task" }
clap = { workspace = true }
extism-pdk = { workspace = true }
schematic = { workspace = true, optional = true, features = [
	"config",
	"json",
	"validate",
] }
serde = { workspace = true }
rustc-hash = { workspace = true }
warpgate_pdk = { workspace = true }

[features]
default = []
schematic = ["dep:schematic"]

[lints]
workspace = true
