[package]
name = "moon_pdk"
version = "0.1.4"
edition = "2024"
license = "MIT"
description = "A plugin development kit for creating moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "0.1.2", path = "../common" }
moon_pdk_api = { version = "0.1.6", path = "../pdk-api" }
moon_project = { version = "0.1.3", path = "../project" }
moon_task = { version = "0.1.2", path = "../task" }
clap = { workspace = true }
extism-pdk = { workspace = true }
serde = { workspace = true }
rustc-hash = { workspace = true }
warpgate_pdk = { workspace = true }

[lints]
workspace = true
