[package]
name = "moon_console"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Console reporting layer."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
miette = { workspace = true }
parking_lot = "0.12.1"
starbase = { workspace = true }
starbase_styles = { workspace = true }
