[package]
name = "moon_input_group"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Input groups for files, globs, and env."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
common-path = "1.0.0"
miette = { workspace = true }
once_cell = { workspace = true }
relative-path = { workspace = true, features = ["serde"] }
serde = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }
