[package]
name = "moon_emitter"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "emitter_benchmark"
harness = false

[dependencies]
moon_action = { path = "../action" }
moon_action_context = { path = "../action-context" }
moon_cache = { path = "../cache" }
moon_error = { path = "../error" }
moon_platform_runtime = { path = "../platform-runtime" }
moon_project = { path = "../project" }
moon_target = { path = "../target" }
moon_task = { path = "../task" }
moon_utils = { path = "../utils" }
moon_workspace = { path = "../workspace" }
async-trait = "0.1.61"
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
moon_test_utils = { path = "../test-utils" }
criterion = { workspace = true }
