[package]
name = "moon_action_pipeline"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "pipeline_benchmark"
harness = false

[dependencies]
moon_action = { path = "../action" }
moon_action_context = { path = "../action-context" }
moon_cache = { path = "../cache" }
moon_dep_graph = { path = "../dep-graph" }
moon_emitter = { path = "../emitter" }
moon_error = { path = "../error" }
moon_hasher = { path = "../hasher" }
moon_logger = { path = "../logger" }
moon_notifier = { path = "../notifier" }
moon_pipeline_provider = { path = "../pipeline-provider" }
moon_platform = { path = "../platform" }
moon_project = { path = "../project" }
moon_project_graph = { path = "../project-graph" }
moon_runner = { path = "../runner" }
moon_target = { path = "../target" }
moon_terminal = { path = "../terminal" }
moon_tool = { path = "../tool" }
moon_utils = { path = "../utils" }
moon_workspace = { path = "../workspace" }
moonbase = { path = "../moonbase" }
proto = { path = "../../proto/cli" }
console = { workspace = true }
rustc-hash = { workspace = true }
rusty_pool = "0.7.0"
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
moon = { path = "../moon" }
moon_test_utils = { path = "../test-utils" }
criterion = { workspace = true }
