[package]
name = "moon_action_pipeline"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
bench = false

[[bench]]
name = "pipeline_benchmark"
harness = false

[dependencies]
moon_action = { path = "../action" }
moon_action_context = { path = "../action-context" }
moon_actions = { path = "../actions" }
moon_api = { path = "../../../nextgen/api" }
moon_cache_item = { path = "../../../nextgen/cache-item" }
moon_dep_graph = { path = "../dep-graph" }
moon_emitter = { path = "../emitter" }
moon_hash = { path = "../../../nextgen/hash" }
moon_logger = { path = "../logger" }
moon_notifier = { path = "../notifier" }
moon_platform = { path = "../platform" }
moon_project = { path = "../../../nextgen/project" }
moon_project_graph = { path = "../../../nextgen/project-graph" }
moon_runner = { path = "../runner" }
moon_target = { path = "../../../nextgen/target" }
moon_terminal = { path = "../terminal" }
moon_tool = { path = "../tool" }
moon_utils = { path = "../utils" }
moon_workspace = { path = "../workspace" }
ci_env = { workspace = true }
console = { workspace = true }
miette = { workspace = true }
num_cpus = "1.16.0"
proto_core = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
moon = { path = "../moon" }
moon_test_utils = { path = "../test-utils" }
criterion = { workspace = true }
