[package]
name = "moon_deno_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_error = { path = "../../core/error" }
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_utils = { path = "../../core/utils" }
cached = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
