[package]
name = "moon_deno_lang"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_typescript_lang = { path = "../../typescript/lang" }
cached = { workspace = true }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }

[lints]
workspace = true
