[package]
name = "moon_rust_lang"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
cached = { workspace = true }
cargo-lock = "10.1.0"
cargo_toml = "0.22.1"
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true, features = ["glob", "toml"] }

[dev-dependencies]
moon_test_utils = { path = "../../core/test-utils" }

[lints]
workspace = true
