[package]
name = "moon_project"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_config = { path = "../config" }
moon_error = { path = "../error" }
moon_logger = { path = "../logger" }
moon_utils = { path = "../utils" }
common-path = "1.0"
globset = "0.4"
globwalk = "0.8"
itertools = "0.10"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.1"
tokio = { version = "1.16", features = ["test-util"] }
