[package]
name = "moon_project"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "A project in moon."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "1.0.1", path = "../common" }
moon_config = { version = "1.0.1", path = "../config" }
moon_file_group = { version = "1.0.1", path = "../file-group" }
moon_task = { version = "1.0.1", path = "../task" }
miette = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
