[package]
name = "moon_target"
version = "0.0.3"
edition = "2021"
license = "MIT"
description = "Project + task target identifier."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
moon_common = { version = "0.0.4", path = "../common" }
miette = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
