[package]
name = "moon_target"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_common = { path = "../common" }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
