[package]
name = "moon_process_augment"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_app_context = { path = "../app-context" }
moon_common = { path = "../common" }
moon_env_var = { path = "../env-var" }
moon_pdk_api = { path = "../pdk-api" }
moon_process = { path = "../process" }
moon_project = { path = "../project" }
moon_task = { path = "../task" }
moon_toolchain = { path = "../toolchain" }
rustc-hash = { workspace = true }
miette = { workspace = true }

[lints]
workspace = true
