[package]
name = "moon_project_graph"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "project_graph_benchmark"
harness = false

[dependencies]
moon_config = { path = "../config" }
moon_error = { path = "../error" }
moon_hasher = { path = "../hasher" }
moon_logger = { path = "../logger" }
moon_platform_detector = { path = "../platform-detector" }
moon_project = { path = "../project" }
moon_target = { path = "../target" }
moon_task = { path = "../task" }
moon_utils = { path = "../utils" }
moon_vcs = { path = "../vcs" }
moon_workspace = { path = "../workspace" }
dotenvy = "0.15.6"
petgraph = {  workspace = true, features = ["serde"] }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
moon = { path = "../moon" }
moon_cache = { path = "../cache" }
moon_test_utils = { path = "../test-utils" }
criterion = { workspace = true }
tokio = { workspace = true }

