[package]
name = "moon_project"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A project (app, lib, etc) in moon."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_input_group = { path = "../input-group" }
moon_task = { path = "../task" }
moon_query = { path = "../query" }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
