[package]
name = "moon_typescript_lang"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_utils = { path = "../../core/utils" }
cached = { workspace = true }
miette = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
typescript_tsconfig_json = { version = "0.1.4", features = ["serialize"] }

[dev-dependencies]
moon_test_utils = { path = "../../core/test-utils" }

[lints]
workspace = true
