[package]
name = "moon_bun_lang"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
cached = { workspace = true }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
tracing = { workspace = true }
yarn-lock-parser = "0.11.0"

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
