[package]
name = "moon_pdk_test_utils"
version = "2.0.0"
edition = "2024"
license = "MIT"
description = "Utilities for testing moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_pdk_api = { version = "2.0.0", path = "../pdk-api" }
moon_target = { version = "2.0.0", path = "../target" }
extism = { workspace = true }
proto_core = { workspace = true }
proto_pdk_test_utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }
warpgate = { workspace = true }

[lints]
workspace = true
