[package]
name = "moon_pdk_test_utils"
version = "0.4.2"
edition = "2024"
license = "MIT"
description = "Utilities for testing moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_pdk_api = { version = "0.4.1", path = "../pdk-api" }
moon_target = { version = "0.2.0", path = "../target" }
extism = { workspace = true }
proto_core = { workspace = true }
proto_pdk_test_utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }
warpgate = { workspace = true }

[lints]
workspace = true
