[package]
name = "moon_pdk_test_utils"
version = "0.0.15"
edition = "2024"
license = "MIT"
description = "Utilities for testing moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_pdk_api = { version = "0.0.14", path = "../pdk-api" }
warpgate = { workspace = true }
extism = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }

[lints]
workspace = true
