[package]
name = "moon_pdk_api"
version = "0.0.3"
edition = "2021"
license = "MIT"
description = "Core APIs for creating moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
moon_common = { version = "0.0.2", path = "../common" }
moon_config = { version = "0.0.3", path = "../config" }
rustc-hash = { workspace = true }
serde = { workspace = true }
warpgate_api = { workspace = true }
