[package]
name = "moon_common"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Common utilities."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
miette = { workspace = true }
once_cell = { workspace = true }
relative-path = { workspace = true }
regex = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
thiserror = { workspace = true }
