[package]
name = "moon_common"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
starbase_styles = { workspace = true }
thiserror = { workspace = true }
