[package]
name = "moon_vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_config = { path = "../config" }
moon_error = { path = "../error" }
moon_utils = { path = "../utils" }
async-trait = "0.1.61"
cached = { workspace = true, features = ["async"] }
ignore = "0.4.19"
regex = "1.7.1"
rustc-hash = { workspace = true }
url = "2.3.1"
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
moon_test_utils = { path = "../test-utils" }
