[package]
name = "moon_workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
moonbase = { path = "../moonbase" }
moon_cache = { path = "../cache" }
moon_config = { path = "../config" }
moon_constants = { path = "../constants" }
moon_error = { path = "../error" }
moon_logger = { path = "../logger" }
moon_platform = { path = "../platform" }
moon_utils = { path = "../utils" }
moon_vcs = { path = "../vcs" }
proto_cli = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
