[package]
name = "moon_target"
version = "2.0.0"
edition = "2024"
license = "MIT"
description = "Project + task target identifier."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "2.0.1", path = "../common" }
compact_str = { workspace = true }
miette = { workspace = true }
regex = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
