[package]
name = "moon_toolchain"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_env_var = { path = "../env-var" }
regex = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
