[package]
name = "moon_task"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "A task within a project."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "1.0.1", path = "../common" }
moon_config = { version = "1.0.1", path = "../config" }
moon_feature_flags = { version = "1.0.1", path = "../feature-flags" }
moon_target = { version = "1.0.1", path = "../target" }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["glob"] }

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
