[package]
name = "moon_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_logger = { path = "../logger" }
console = { workspace = true }
dialoguer = "0.10.2"
lazy_static = { workspace = true }
regex = "1.7.0"
