[package]
name = "moon_typescript_platform"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_common = { path = "../../../crates/common" }
moon_config = { path = "../../../crates/config" }
moon_hash = { path = "../../../crates/hash" }
moon_node_lang = { path = "../../node/lang" }
moon_project = { path = "../../../crates/project" }
moon_utils = { path = "../../core/utils" }
moon_typescript_lang = { path = "../lang" }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
tracing = { workspace = true }

[dev-dependencies]
moon_common = { path = "../../../crates/common" }
moon_test_utils = { path = "../../core/test-utils" }

[lints]
workspace = true
