[package]
name = "moon_project_expander"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Expands projects and tasks with runtime information."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_args = { path = "../args" }
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_project = { path = "../project" }
moon_task = { path = "../task" }
moon_task_args = { path = "../task-args" }
moon_time = { path = "../time" }
dotenvy = "0.15.7"
miette = { workspace = true }
pathdiff = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }

[lints]
workspace = true
