[package]
name = "moon_python_lang"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
cached = { workspace = true }
miette = { workspace = true }
pep-508 = "0.4.0"
rustc-hash = { workspace = true }

[dev-dependencies]
moon_test_utils = { path = "../../core/test-utils" }

[lints]
workspace = true
