[package]
name = "moon_action_context"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_common = { path = "../../../nextgen/common" }
moon_target = { path = "../../../nextgen/target" }
clap = { workspace = true }
relative-path = { workspace = true, features = ["serde"] }
rustc-hash = { workspace = true }
serde = { workspace = true }
