[package]
name = "moon_utils"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_common = { path = "../../../crates/common" }
moon_logger = { path = "../logger" }
async-trait = { workspace = true }
cached = { workspace = true }
chrono = { workspace = true }
clean-path = "0.2.1"
dunce = "1.0.4"
humantime = "2.1.0"
md5 = "0.7.0"
miette = { workspace = true }
once_cell = { workspace = true }
pathdiff = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
rustc-hash = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
moon_test_utils = { path = "../test-utils" }

[lints]
workspace = true
