[package]
name = "moon_mcp"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "MCP utilities for interacting with AI agents."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_action = { path = "../action" }
moon_action_graph = { path = "../action-graph" }
moon_action_pipeline = { path = "../action-pipeline" }
moon_app_context = { path = "../app-context" }
moon_common = { version = "0.2.0", path = "../common" }
moon_project = { version = "0.2.0", path = "../project" }
moon_task = { version = "0.2.0", path = "../task" }
moon_workspace_graph = { path = "../workspace-graph" }
async-trait = { workspace = true }
miette = { workspace = true }
rust-mcp-sdk = { version = "0.7.0", default-features = false, features = [
	"macros",
	"server",
	"stdio",
	"2025_06_18",
] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
