[package]
name = "moon_deno_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_action_context = { path = "../../core/action-context" }
moon_config = { path = "../../core/config" }
moon_deno_lang = { path = "../lang" }
moon_deno_tool = { path = "../tool" }
moon_error = { path = "../../core/error" }
moon_hasher = { path = "../../core/hasher" }
moon_logger = { path = "../../core/logger" }
moon_platform = { path = "../../core/platform" }
moon_project = { path = "../../core/project" }
moon_task = { path = "../../core/task" }
moon_terminal = { path = "../../core/terminal" }
moon_tool = { path = "../../core/tool" }
moon_utils = { path = "../../core/utils" }
proto_cli = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
moon = { path = "../../core/moon" }
moon_project_graph = { path = "../../core/project-graph" }
moon_test_utils = { path = "../../core/test-utils" }
