[package]
name = "moon_task"
version = "0.1.0"
edition = "2021"

[dependencies]
moon_config = { path = "../config" }
moon_error = { path = "../error" }
moon_logger = { path = "../logger" }
moon_target = { path = "../../../nextgen/target" }
moon_utils = { path = "../utils" }
common-path = "1.0.0"
once_cell = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
moon_test_utils = { path = "../test-utils" }
